Expecting "file" after import.
got: identifier: some_identifier [4:8..22]
Caught exception from lexer, aborting parsing.
